require File.expand_path(File.dirname(__FILE__) + '/spec_helper')
require 'message_collector'
require 'minecraft'

describe MessageCollector do
	it 'should collect messages via passed proc call' do
		mc = MessageCollector.new do |collector|
			collector.call(:test1)
			collector.call(:test2)
		end

		msgs = []
		mc.each do |msg|
			msgs << msg
		end

		msgs.should == [:test1, :test2]
	end

	describe 'with minecraft running' do
		before :all do
			@m = Minecraft.new(File.dirname(__FILE__) + '/stub_server/minecraft')
			@m.start
		end

		it 'should collect messages generated by minecraft commands' do
			msgs = []

			MessageCollector.new do |collector|
			@m.with_message_collector(collector) do
				list
				command(:help)
			end
			end.each do |msg|
				msgs << msg.msg
			end

			msgs.first.should == 'Connected players: kazuya'
			msgs.should include 'Console commands:'
		end

		it 'should provide #for method that shortens the code' do
			msgs = []

			MessageCollector.for(@m) do
				list
				command(:help)
			end.each do |msg|
				msgs << msg.msg
			end

			msgs.first.should == 'Connected players: kazuya'
			msgs.should include 'Console commands:'
		end

		after :all do
			@m.stop
		end
	end
end

